runtime: python38 # or another supported version
instance_class: F1 # this is the cheapest option
env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: gunnjvgirls
  MYSQL_DB: bballdb
  MYSQL_HOST: 34.121.178.35
handlers:
- url: /script
  static_dir: static/script
- url: /styles
  static_dir: static/styles